### ISSUE TITLE
Error when adding negative floating point values in formula interpreter

### ISSUE THREAD

**Issue by HuubBuis** [FreeCAD/FreeCAD-Bundle#109]
Freecad 0.20, revision 28611, Windows 10 
When a using a formula in a constrain to add two values, I get an error when one of the values is a **negative float**. The error is in the properties and in the spreadsheet.
The tooltip shows: can only concatenate str (not "int" to str)
 As a workaround I enter the values in the spreadsheet  as: "=-0.1"

Spreadsheet Example: using int:
B1 1 ; B2 2 ; B3 =B1+B2 ; result 3

Spreadsheet Example: using float:
B1 1.0 ; B2 2 ; B3 =B1+B2 ; result = 3

Spreadsheet Example: using negative float:
B1 -1.0 ; B2 2 ; B3 =B1+B2 ; result=error

Spreadsheet Example: workaround: add an assignment sign before the value
B1 **=**-1.0 ; B2 2 ; B3 =B1+B2 ; result=1

I have attached a spreadsheet showing the error.
[Freecad formula interpreter error.zip](https://github.com/FreeCAD/FreeCAD-Bundle/files/8532416/Freecad.formula.interpreter.error.zip)

**Comment by luzpaz** [comment]
Wrong place. Please open a forum.freecad.org thread first. Then the community will vet it before opening a ticket on the correct bugtracker
