### ISSUE TITLE
Old weekly build for Windows

### ISSUE THREAD

**Issue by dasarne** [FreeCAD/FreeCAD-Bundle#112]
The version of the weekly build for Windows is significantly older than the one for Linux. (0.20.27422)

**Comment by luzpaz** [comment]
Known issue: the LP (LibPack) version is not built with Conda. Currently there is a problem with LibPack, a 3rd party dependency conflict that the packagers haven't sorted out yet. It's actually holding up the release of v0.20. 

Closing issue.
