### ISSUE TITLE
AppImage: fails to remote update due to 'zsync control file was not found in the specific location' 

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-Bundle#116]
![Screenshot_20220529_070316](https://user-images.githubusercontent.com/4140247/170864739-f2ebf8f7-87f5-45f3-8ffd-bad920a0745e.png)

Was there a change made to appimage names or something recently?

**Comment by adrianinsaval** [comment]
There were changes to the names but I don't know if that affects this

**Comment by adrianinsaval** [comment]
What to do with this issue? I don't think anything can be done retroactively on the appimages that won't update and the newer ones work.

**Comment by luzpaz** [comment]
Good point. Closing
