### ISSUE TITLE
Appimage reports incorrect commit hash

### ISSUE THREAD

**Issue by adrianinsaval** [FreeCAD/FreeCAD-Bundle#117]
see: https://forum.freecadweb.org/viewtopic.php?f=3&t=40675&p=601043#p601043
the appimage is reporting the commit hash from the freecad-feedstcok repo instead of the FreeCAD repo, this is not helpful info

**Comment by adrianinsaval** [comment]
my theory is that when building the source is extracted in a directory inside the feedstock repo so the script that is run by cmake to get the git info grabs it from the feedstock repo, if the source was placed somewhere outside this repo before building this should be solved

**Comment by luzpaz** [comment]
Anyone know where is the code for this located?

**Comment by adrianinsaval** [comment]
https://github.com/looooo/freecad-feedstock I think but I don't understand how it works so I don't know what files need editing

**Comment by adrianinsaval** [comment]
Another probably easier option is to apply this patch before compiling:
```
diff --git a/src/Tools/SubWCRev.py b/src/Tools/SubWCRev.py
index 195d0facc3..49e0ff8658 100644
--- a/src/Tools/SubWCRev.py
+++ b/src/Tools/SubWCRev.py
@@ -459,7 +459,7 @@ def main():
             inp = open("%s/src/Build/Version.h.in" % (bindir))
             lines = inp.readlines()
             inp.close()
-            lines = i.writeVersion(lines)
+            #lines = i.writeVersion(lines)
             out  = open("%s/src/Build/Version.h.out" % (bindir),"w");
             out.writelines(lines)
             out.write('\n')

```
then it won't write the git info it found onto Version.h.in

**Comment by chennes** [comment]
The tool that generates the hash is here (on Linux): https://github.com/FreeCAD/FreeCAD/blob/master/src/Tools/SubWCRev.py

**Comment by adrianinsaval** [comment]
made a PR with the patch I suggested

**Comment by luzpaz** [comment]
Thanks @adrianinsaval !
