### ISSUE TITLE
Text of weekly-builds download page is innacurate

### ISSUE THREAD

**Issue by DuncanLithgow** [FreeCAD/FreeCAD-Bundle#125]
https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/weekly-builds

The current text for windows download is:

> There are different versions for windows
> 3.1 Bundles created using conda (need to be unzipped)
> 3.2 LP (libpack) bundles using FreeCAD's own libpack.
> 3.2.1 exe: installer
> 3.2.2 zip: Bundles that need to be unzipped.

But that is not what is actually available, what's available is only a .7z download (which is not a zip file, it's an archive). 

I'm happy to send a pull request with a more accurate text.

**Comment by luzpaz** [comment]
Thanks @DuncanLithgow !
Please add revised text to this ticket?

**Comment by DuncanLithgow** [comment]
For Linux the Appimages (conda-based) run on most distributions
For OSX download the Dmg's (conda-based)
For Windows download and unpack the 7zip archive

**Comment by DuncanLithgow** [comment]
@luzpaz text suggestion is in previous comment

**Comment by luzpaz** [comment]
@DuncanLithgow sorry, updated! Thanks! 
Closing
