### ISSUE TITLE
 FreeCAD_weekly-builds-29865-2022-07-31 Windows is missing

### ISSUE THREAD

**Issue by bgma** [FreeCAD/FreeCAD-Bundle#129]
Hi,
I Can't find any windows-weekly build,
Something wrong?

**Comment by adrianinsaval** [comment]
https://github.com/FreeCAD/FreeCAD-Bundle/issues/126#issuecomment-1200262151

this issue is then a duplicate, also keep in mind that github sometimes fails to upload assets for no reason so maybe it's not worth creating an issue unless an asset is missing for at least two releases

**Comment by looooo** [comment]
windows is failing because of two issues at the moment:
1. coin can't be found by make
2. smesh is not properly linked
