### ISSUE TITLE
osx-arm

### ISSUE THREAD

**Issue by looooo** [FreeCAD/FreeCAD-Bundle#131]
- [x] FreeCAD logo not working
- [x] dmg version name is wrong (the actual version is higher than 29436) bundling process needs to run on m1 directly

**Comment by adrianinsaval** [comment]
Running in an automated way in an M1 might be hard to achieve right now (github doesn't have arm runners AFAIK), is this needed only to get info version?

**Comment by looooo** [comment]
No it's also needed to compile freecad. There are some more issues with cross-compiling. There are some instructions to setup GitHub action runners locally. Maybe this would be an idea to further improve automatisation of osx-arm64 and linx aarch64.

**Comment by looooo** [comment]
at the moment I do the osx-arm builds and bundles locally, waiting for GitHub-action to offer osx-arm64 support.

**Comment by sammcj** [comment]
Any updates to this? It's still an issue and the only decent performing build is that single arm build from December.

**Comment by JohnOCFII** [comment]
> Any updates to this? It's still an issue and the only decent performing build is that single arm build from December.

Watch this thread.  There is now a working Conda build as of today.  https://forum.freecad.org/viewtopic.php?t=76777&start=20

**Comment by sammcj** [comment]
That's awesome news! Thank you! 😄
