### ISSUE TITLE
Appimage not signed

### ISSUE THREAD

**Issue by leoheck** [FreeCAD/FreeCAD-Bundle#134]
I am upgrading the Freecad Weekly with the Appimage upgrade tool.

Last week I did not have this issue. 

![image](https://user-images.githubusercontent.com/1277920/189460261-cc84d5f6-5829-4631-b5f4-2c5ae6f5ea08.png)

**Comment by luzpaz** [comment]
Related #6

**Comment by adrianinsaval** [comment]
> Last week I did not have this issue.

that's strange, AFAIK the appimage never got signed.

**Comment by leoheck** [comment]
Exactly what I thought. But at that time, the installation did not complained and the progress bar turned green instead of yellow. Maybe it was a different version of the updater tool then. Unfortunately I cannot check this anymore. I can only get the current version I am using.

**Comment by adrianinsaval** [comment]
duplicate of #6 and this should be solved for x86_64 now
