### ISSUE TITLE
vtk result export units conversion problem

### ISSUE THREAD

**Issue by HoSoon-Choi** [FreeCAD/FreeCAD-Bundle#135]
Version 020.1 vtk result export may have units conversion problem.
In displacement result, model size unit is in mm, but displacement result unit is in m.
In stress result, result unit changed to Pa.

Next image is displacement result from 020.1 vtk result export.
![020_1](https://user-images.githubusercontent.com/94062419/191735457-622c36e1-6862-4228-b2d4-624a5ac9e28c.png)

Displcement result from calculix vtk export.
![calculix](https://user-images.githubusercontent.com/94062419/191735536-f266f714-2e66-463a-a602-e6ef46b5910c.png)

Von Mises stress result from 020.1 vtk result export.
![020_1stress](https://user-images.githubusercontent.com/94062419/191735547-fc1a0e42-08e4-4d73-9686-e1ebac6e6b64.png)

Von Mises stress result from calculix vtk export.
![calculix_stress](https://user-images.githubusercontent.com/94062419/191735566-8f698fb6-8f69-45dd-b6ad-1610d46694d3.png)

**Comment by luzpaz** [comment]
Wrong place for this. Let the FEM folk know on the forum: https://forum.freecadweb.org/viewforum.php?f=18
