### ISSUE TITLE
Update weekly builds to OCC 7.7.0

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-Bundle#142]
See https://github.com/FreeCAD/FreeCAD-snap/issues/69

**Comment by adrianinsaval** [comment]
here's the repo for the occt conda builds: https://github.com/conda-forge/occt-feedstock

**Comment by looooo** [comment]
this will need some time. currently there is work needed for python3.11 / boost / vtk. python3.11 is the most interesting update here as it is faster. Not sure about occt.

**Comment by maxwxyz** [comment]
Is this still relevant?

**Comment by adrianinsaval** [comment]
we're using 7.7.2 now, have to work on updating to 7.8.0 now
