### ISSUE TITLE
 Qt WebEngine locales directory not found on latest "weekly"

### ISSUE THREAD

**Issue by erickwill** [FreeCAD/FreeCAD-Bundle#153]
Got this message on the latest "weekly" Windows version:

15:14:20  Installed Qt WebEngine locales directory not found at location C:/Users/erick/Documents/Apps/FreeCAD_weekly-builds-31625-2023-01-19-conda-Windows-x86_64-py310/translations\qtwebengine_locales. Trying application directory...
15:14:20  Qt WebEngine locales directory not found at location C:/Users/erick/Documents/Apps/FreeCAD_weekly-builds-31625-2023-01-19-conda-Windows-x86_64-py310/bin\qtwebengine_locales. Trying fallback directory... Translations MAY NOT not be correct. 

Lemme know if any log is necessary beyond this error message.
Thanks

Ps. On the Linux weekly version everything is nice.

**Comment by adrianinsaval** [comment]
this has been fixed
