### ISSUE TITLE
Urgent: Weekly builds filenames are not getting updated (except Windows Libpack)

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-Bundle#156]
FreeCAD master is at: 32111 commits but generated weeklies are not reflecting the build number correctly. They should all be in the ~32000 range as can be seen in the Windows Libpack.   
 
![Screenshot_20230227_065626](https://user-images.githubusercontent.com/4140247/221558358-bf1d1806-b764-468d-8058-7d4dc599c21c.png)

**Comment by luzpaz** [comment]
This is related to #122

**Comment by vernzimm** [comment]
https://forum.freecad.org/viewtopic.php?t=76338

Referenced here, but hopefully the issue I created for looooo is where it needs to be fixed.

**Comment by adrianinsaval** [comment]
the names are not updated because the conda package is not updated

**Comment by adrianinsaval** [comment]
#122 has nothing to do with this

**Comment by luzpaz** [comment]
> the names are not updated because the conda package is not updated

Do you mind elaborating?

**Comment by adrianinsaval** [comment]
https://forum.freecad.org/viewtopic.php?t=76795
quoting myself:

> No the commit hash corresponds to that revision number plus we can see on the repo where the conda package is made that the compilations are failing: [https://github.com/looooo/freecad-feeds ... its/master](https://github.com/looooo/freecad-feedstock/commits/master) (click the red X on each commit to see more details)
> 
> The bundle shows as published yesterday because it is made automatically and it's just creating a bundle from the latest version available, it does not know if that version is the same as it already was uploaded so it just uploads again.
