### ISSUE TITLE
snap 3D parts

### ISSUE THREAD

**Issue by kberkut** [FreeCAD/FreeCAD-Bundle#157]
Not work move part when use snapping.

[Запись экрана от 2023-03-22 12-06-36.webm](https://user-images.githubusercontent.com/57869227/226854544-6398f13b-b6d7-4d41-befa-5b6031297603.webm)

`
OS: Arch Linux (GNOME/gnome)
Word size of FreeCAD: 64-bit
Version: 0.20.2.29603 (Git)
Build type: Release
Branch: makepkg
Hash: 930dd9a76203a3260b1e6256c70c1c3cad8c5cb8
Python 3.10.9, Qt 5.15.8, Coin 4.0.1, Vtk 9.2.6, OCC 7.6.3
Locale: Russian/Russia (ru_RU)
Installed mods: 
  * fasteners 0.4.55
  * Manipulator 1.5.0
  * Help 1.0.3
  * Assembly4 0.12.6
  * A2plus 0.4.60k
  * sheetmetal 0.2.61
  * LCInterlocking
`

`
OS: Arch Linux x86_64
Host: 81NC Lenovo IdeaPad S340-15API
Kernel: 6.2.7-arch1-1
Uptime: 2 hours, 53 mins
Packages: 1858 (pacman), 14 (flatpak)
Shell: zsh 5.9
Resolution: 1920x1080
DE: GNOME 43.3
WM: Mutter
WM Theme: Adwaita 
Theme: Adwaita [GTK2/3] 
Icons: Faenza [GTK2/3] 
Terminal: qterminal 
Terminal Font: DejaVu Sans Mono 12 
CPU: AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx (8) @ 2.100GHz 
GPU: AMD ATI Radeon Vega Series / Radeon Vega Mobile Series 
Memory: 4438MiB / 9886MiB
`

**Comment by adrianinsaval** [comment]
This is not the place to ask this, please go to the help forum instead: https://forum.freecad.org/viewforum.php?f=3
the problem here is that when selecting in 3d view you select the underlying PD feature (which can't be moved) not the body (which can be moved).
