### ISSUE TITLE
Qt WebEngine errors on Windows 11

### ISSUE THREAD

**Issue by erickwill** [FreeCAD/FreeCAD-Bundle#161]
From a few releases, almost a month ago, I started to have these issues: 

Qt WebEngine locales directory not found at location C:/Users/erick/Documents/Apps/FreeCAD_weekly-builds-32532-2023-03-26-conda-Windows-x86_64-py310/bin\qtwebengine_locales. Trying fallback directory... Translations MAY NOT not be correct.

Installed Qt WebEngine locales directory not found at location C:/Users/erick/Documents/Apps/FreeCAD_weekly-builds-32532-2023-03-26-conda-Windows-x86_64-py310/translations\qtwebengine_locales. Trying application directory...

Any fix or workaround?
I'm running the FreeCAD_weekly-builds-32532-2023-03-26-conda-Windows-x86_64-py310 under an up-to-dated Windows 11.

**Comment by chennes** [comment]
Should be fixed by #162.

**Comment by adrianinsaval** [comment]
since this is fixed, I'm closing this issue
