### ISSUE TITLE
Windows version does not start

### ISSUE THREAD

**Issue by Pendelf** [FreeCAD/FreeCAD-Bundle#167]
I tried on several computers, several released versions and not one started, the process just weighs in the background

**Comment by adrianinsaval** [comment]
this is not the place to voice general concerns, this repository deals exclusively with packaging and you won't get much help here. Your post is also severely lacking information.

please make a new thread on the help request forum instead: https://forum.freecad.org/viewforum.php?f=3

before taht please check the knonw issues post: https://forum.freecad.org/viewtopic.php?t=30573
search for existing topics and read the guidelines: https://forum.freecad.org/viewtopic.php?f=3&t=2264
