### ISSUE TITLE
Conda: Weekly MacOS ARM build requires Rosetta

### ISSUE THREAD

**Issue by alber70g** [FreeCAD/FreeCAD-Bundle#168]
I just downloaded the latest weekly for MacOS ARM but it requires Rosetta to launch.

FreeCAD_weekly-builds-31483-2022-12-31-conda-macOS-arm-py311

**Comment by JohnOCFII** [comment]
This recently updated process allows me to build and run FreeCAD on my M1 arm Mac.  My understanding is that this was going to be integrated into the automated build process for weekly builds, because as you can see from the date above -- that arm build is quite old.  

https://github.com/oursland/FreeCAD-Build-Notes

I'm not sure what remains before the steps in that process can be integrated into the weekly automated build process.

**Comment by luzpaz** [comment]
Wow, excellent effort in https://github.com/oursland/FreeCAD-Build-Notes !

> I'm not sure what remains before the steps in that process can be integrated into the weekly automated build process.

How do you suggest we ascertain that?

**Comment by realthunder** [comment]
I happen to be working on github auto build recently. I managed to make it work to [cross compile](https://github.com/realthunder/FreeCAD/blob/LinkMerge/.github/workflows/conda.yml) osx arm conda package on github intel machine. But to my understanding, we still need a real osx arm machine to make the bundle, which github does not offer at the moment. There is only commercial alternatives, which are not cheap. I am curious to see if anyone has any way around it. Or, maybe find some one to volunteer his personal osx arm machine as a [self-hosted](https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners) github runner.

**Comment by luzpaz** [comment]
> I am curious to see if anyone has any way around it. Or, maybe find some one to volunteer his personal osx arm machine as a [self-hosted](https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners) github runner.

Sound something that the FPA should be involved in ?

**Comment by JohnOCFII** [comment]
> How do you suggest we ascertain that?

@oursland may have some ideas.

**Comment by chennes** [comment]
I have an M1 that we can use as a self-hosted runner, someone just needs to tell me what I need to do to set such a thing up.

**Comment by luzpaz** [comment]
@realthunder looks like chennes is game :tada:

**Comment by alber70g** [comment]
Is it possible to add a new ARM64 build for MacOS to either weekly or 0.20.2 (https://github.com/FreeCAD/FreeCAD-Bundle/releases)?

**Comment by adrianinsaval** [comment]
can we emulate arm on a github action?

**Comment by chennes** [comment]
We don't need any emulation, I just need to set up a self-hosted runner -- I have a lot of balls in the air right now, though, so it hasn't made my priority list.

**Comment by adrianinsaval** [comment]
can you run linux and windows vms on it too?

**Comment by chennes** [comment]
Yes, but I haven't tried compiling on Windows because Visual Studio doesn't support running on ARM (you are supposed to cross-compile from x86).

**Comment by adrianinsaval** [comment]
> Yes, but I haven't tried compiling on Windows because Visual Studio doesn't support running on ARM (you are supposed to cross-compile from x86).

that is so stupid but I don't know what I was expecting from MS

> We don't need any emulation, I just need to set up a self-hosted runner -- I have a lot of balls in the air right now, though, so it hasn't made my priority list.

I think there is a runner available in azure to get mac arm builds but it keeps failing, we could use emulation for the bundling process that happens here on github

**Comment by adrianinsaval** [comment]
I have uploaded a new arm bundle, can you try if it also asks for rosetta? https://github.com/FreeCAD/FreeCAD-Bundle/releases/download/weekly-builds/FreeCAD_weekly-builds-33447-2023-06-26-conda-macOS-arm-py310.dmg

**Comment by JohnOCFII** [comment]
> I have uploaded a new arm bundle, can you try if it also asks for rosetta? https://github.com/FreeCAD/FreeCAD-Bundle/releases/download/weekly-builds/FreeCAD_weekly-builds-33447-2023-06-26-conda-macOS-arm-py310.dmg

Seems to work fine on my M1 MacBook Pro.  Activity Viewer shows it at an Apple (arm) binary. I saw no request for Rosetta.  FYI - It only shows the generic App icon.  
<img width="107" alt="Screenshot 2023-06-26 at 10 19 46 AM" src="https://github.com/FreeCAD/FreeCAD-Bundle/assets/7844212/41fef0f7-0c80-481b-af67-4b41e53d8dd2">


```
OS: macOS 13.4.1
Word size of FreeCAD: 64-bit
Version: 0.21.0.33447 (Git)
Build type: Release
Branch: master
Hash: 090ae4571a589171dccb5dcabaf9d71e453ab2f3
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.7.1
Locale: C/Default (C)
```

**Comment by adrianinsaval** [comment]
Good, probably the other bundle was at least partially cross compiled and that's why it asks for Rosetta, I had this version compiled using cirrus-ci's M1 runners and then bundled in chennes' M1 machine so it should be all native.
I don't know about the icon, would have to look into how that's supposed to be specified but would love it if any of the Mac connoisseurs could lend me a hand there

**Comment by JohnOCFII** [comment]
> I don't know about the icon, would have to look into how that's supposed to be specified but would love it if any of the Mac connoisseurs could lend me a hand there

Looking in the package contents, comparing it to a recent Intel Mac build, there are 3 `icns` files that need to be in the Resources directory.  These are currently (properly) referenced from the Info.plist file.  I copied over the 3 files, but that alone didn't seem to make the icon show up, so we'll need some one with real Mac developer background to explain how to hook them up properly.

<img width="709" alt="Screenshot 2023-06-26 at 11 39 23 AM" src="https://github.com/FreeCAD/FreeCAD-Bundle/assets/7844212/a283ae55-20b8-4134-8654-4d76edc7a168">
