### ISSUE TITLE
last couple of Linux dev builds really slow to launch

### ISSUE THREAD

**Issue by broettge** [FreeCAD/FreeCAD-Bundle#169]
The last few development  0.21.0 versions of FreeCAD that I have downloaded from https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/weekly-builds have been really slow on startup.  I noticed that the "Loading FreeCAD GUI" step in the splash screen takes 30-60 seconds and my CPU is at 100% for the freecad process.    The 0.20.2 stable release takes only a couple of seconds to completely load on my system.

I am running a completely updated Arch Linux system (6.2.11)
FreeCAD_weekly-builds-32867-2023-04-16-conda-Linux-x86_64-py310.AppImage is the most recent file where I have had this issue.  It was also present in the others that I downloaded the last couple of weeks.

As an aside, the development weekly-builds download page directs people to report issue using the forum, but does not have any link to the appropriate sub-forum or topic.  The one topic I found said to post a issue here.  It would be much easier to report issues/bugs if there were clear and concise directions (and links) to do so.

**Comment by luzpaz** [comment]
Can you pinpoint what AppImage FreeCAD development build the issue started with ?

**Comment by broettge** [comment]
Unfortunately I don't keep multiple copies of the weekly (daily) appimage builds on my machine and I can't find them too download again.  If you can provide links, I can do some further investigation to help pinpoint when it started happening.

I had been using an appimage that was about a month old and I thought I would try out the newer builds.  I have tried about 3 different ones over the past week and they were all affected.    I also noticed delays in opening the sketcher (along with 100% cpu usage) with these builds.  

If you point

**Comment by broettge** [comment]
I am not sure if you did anything to fix this issue, but it is no longer occurring on my computer with the latest build.
I had to do a fresh install of Linux and when I downloaded and tried the latest build it was working just fine.

**Comment by luzpaz** [comment]
Thanks for the feedback!
