### ISSUE TITLE
AppImage: graphical problem - menu items

### ISSUE THREAD

**Issue by TJFOE** [FreeCAD/FreeCAD-Bundle#172]
I had been working fine with the AppImage "FreeCAD_0.19-22756-Linux-Conda_glibc2.12" last time. Only today I wanted to update to "FreeCAD_0.20.2-2022-12-27-conda-Linux-x86_64-py310".

Today it turns out that there is probably a graphical problem with this new version: menu items are cut off. See attachments. Also glxinfo.txt.

I am on current Manjaro 64 bit Gnome, python-pivy is installed.

I saw that tha package is still in the Manjaro repository and I installed it: The same problem...

[glxinfo.txt](https://github.com/FreeCAD/FreeCAD-Bundle/files/11330609/glxinfo.txt)
![FreeCAD_0_20_2_pic1](https://user-images.githubusercontent.com/10260152/234513787-05eb1a02-19c7-4d69-b01f-66c1bd49ea4b.jpg)
![FreeCAD_0_20_2_pic2](https://user-images.githubusercontent.com/10260152/234513852-d71d90ab-cbec-483f-aa42-9799d32b0cd0.jpg)

**Comment by luzpaz** [comment]
Can you reproduce on the development version, btw ?

**Comment by TJFOE** [comment]
Which version do you mean? I know only the AppImage and the version I installed through the repositories today.

**Comment by TJFOE** [comment]
This one works fine again! Thank you!

FreeCAD_weekly-builds-32985-2023-04-23-conda-Linux-x86_64-py310.AppImage

**Comment by lissyx** [comment]
FTR this is also an issue I have been hitting on `FreeCAD_0.20.2-2022-12-27-conda-Linux-x86_64-py310` trying to run under Ubuntu 22.10 and now 23.04. Current weekly build does not exhibit this behavior.

![image](https://user-images.githubusercontent.com/1645737/235175162-3e56776d-ad0f-46f1-985e-640abcda27dc.png)

**Comment by lissyx** [comment]
> FTR this is also an issue I have been hitting on `FreeCAD_0.20.2-2022-12-27-conda-Linux-x86_64-py310` trying to run under Ubuntu 22.10 and now 23.04. Current weekly build does not exhibit this behavior.
> 
> ![image](https://user-images.githubusercontent.com/1645737/235175162-3e56776d-ad0f-46f1-985e-640abcda27dc.png)

This seems to be fixed now with the `0.21.0` release !
