### ISSUE TITLE
New conda-Linux-x86_64-py311?

### ISSUE THREAD

**Issue by robouden** [FreeCAD/FreeCAD-Bundle#174]
Is there a new FreeCAD_conda-Linux-x86_64-py311 appimage  available?

Regards,
Rob Oudendijk

**Comment by erickwill** [comment]
Good question. Is there any new appimage? 
Thanks and regards

**Comment by chennes** [comment]
@looooo it looks like this is stuck, do you know what's happening?

**Comment by adrianinsaval** [comment]
there is one available now
