### ISSUE TITLE
macOS arm64 bundle - app icon missing, can not rename app

### ISSUE THREAD

**Issue by dirkolbrich** [FreeCAD/FreeCAD-Bundle#189]
The current bundle [FreeCAD_weekly-builds-33458-2023-06-28-conda-macOS-arm64-py310.dmg](https://github.com/FreeCAD/FreeCAD-Bundle/releases/download/weekly-builds/FreeCAD_weekly-builds-33458-2023-06-28-conda-macOS-arm64-py310.dmg) is missing the app icon.

And it is not possible to rename the app to a versioned name, e.g. rename to `FreeCAD-v0.21.33458_arm64_py310.app`. After renaming the app will not start and instead a pop-up window will open, stating that the app can not be opened as it is damaged or incomplete.

After renaming the app back to `FreeCAD.app`, the app will open just fine.

This issues where not present with the previous release bundle `FreeCAD_weekly-builds-31483-conda-macOS-arm64-py311.dmg`.

**Comment by dirkolbrich** [comment]
referencing #144

**Comment by adrianinsaval** [comment]
the bundle should now have an icon. Is the renaming problem still present?

**Comment by dirkolbrich** [comment]
The issue is fixed. The app has an icon and can be renamed.
Tested with:
[code]
OS: macOS 13.4.1
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.33848 (Git)
Build type: Release
Branch: master
Hash: 312975edba4e5af0ca1348bfdcf3a71567c52c1b
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: C/Default (C)
Installed mods: 
  * ProDarkThemePreferencePack 1.0.0
  * BIM 2021.12.0
[/code]

Thank you.
