### ISSUE TITLE
Alert: .FCStd#` backup format is deprecated from 0.21 and may be removed in future versions. Please use `.FCBak` instead.

### ISSUE THREAD

**Issue by erickwill** [FreeCAD/FreeCAD-Bundle#193]
Since 3 builds ago I started to get this message when the app is loaded:

13:54:42  `.FCStd#` backup format is deprecated from 0.21 and may be removed in future versions. Please use `.FCBak` instead.

Please, let me know if any other information or log is necessary. 
Thanks

**Comment by erickwill** [comment]
![Screenshot from 2023-07-27 12-33-16](https://github.com/FreeCAD/FreeCAD-Bundle/assets/549381/74251eb2-bbc2-4b53-a34f-9c25916c5d11)

**Comment by srhart** [comment]
Updating preferences (General>Document>Use date and FCBak) as described in meassage removes this warning. Build 33682.

**Comment by chennes** [comment]
I've clarified the warning in the release to make this less obscure.
