### ISSUE TITLE
Missing FreeCADGui.dll in windows conda build

### ISSUE THREAD

**Issue by ghost** [FreeCAD/FreeCAD-Bundle#200]
Hi, my name luigi from italy .. download freecad version: FreeCAD_weekly-builds-35081-2023-11-20-conda-Windows-x86_64-py310.7z
with freecad 0.21.1 installed.. my show error:

![image](https://github.com/FreeCAD/FreeCAD-Bundle/assets/123329788/9f5a5f86-8296-4a85-8210-3a4fdc5eea9d)

My freecad installed:
```
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.21.1.33668 +26 (Git)
Build type: Release
Branch: (HEAD detached at 0.21.1)
Hash: f6708547a9bb3f71a4aaade12109f511a72c207c
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: Italian/Italy (it_IT)
Installed mods: 
  * A2plus 0.4.61
  * Curves 0.6.14
  * Fasteners 0.4.70
  * gears 1.0.0
  * Pyramids-and-Polyhedrons
  * SheetMetal 0.3.12
```

Idea?
Thanks.

**Comment by YosypC** [comment]
The message translates as "The procedure entry point [...] could not be located in the dynamic link library [...]"

**Comment by luzpaz** [comment]
@adrianinsaval any idea ?

**Comment by adrianinsaval** [comment]
I suspect this is solved. Possibly related to coin 4.0.1 changes. @amorfiniluigi82 can you retry on the latest bundle?

**Comment by luzpaz** [comment]
@amorfiniluigi82 please report back
