### ISSUE TITLE
Assembly4>Animator>Save complains OpenCV not installed - actual problem is pillow

### ISSUE THREAD

**Issue by ppemawm** [FreeCAD/FreeCAD-Bundle#208]
@adrianinsaval
Assembly4 animator save function complains that CV2 is not installed and prevents saving the animation when in fact CV2 is installed.
Error occurs in certain stable and weekly releases referenced in discussions below.

Please see discussions here:
https://forum.freecad.org/viewtopic.php?p=733824#p733824
https://forum.freecad.org/viewtopic.php?p=732390#p732390
https://forum.freecad.org/viewtopic.php?p=726914#p726914

**Comment by adrianinsaval** [comment]
As mentioned in the forum thread opencv doesn't seem to be the problem if it is incorrectly reported by asm4. The actual problem is with pillow that has removed qt5 support in version 10.0

**Comment by adrianinsaval** [comment]
uploaded pillow 9.5 pacakges to conda: https://anaconda.org/freecad/pillow/files
new bundles should be up shortly and I confirmed at least the appimage works:
![animation](https://github.com/FreeCAD/FreeCAD-Bundle/assets/36372335/80598fe7-5232-41aa-b614-48888832ed6b)
