### ISSUE TITLE
Weekly build macOS ARM - Replace uses of missing font family "Courier"

### ISSUE THREAD

**Issue by boboxx** [FreeCAD/FreeCAD-Bundle#212]
I keep getting this error message when I run FreeCad:

10:08:47  (qt.qpa.fonts) Populating font family aliases took 67 ms. Replace uses of missing font family "Courier" with one that exists to avoid this cost.

**Comment by adrianinsaval** [comment]
Can you try if it happens with a clean config?

**Comment by boboxx** [comment]
I have deleted the config folder from /Users/User1/Library/Application Support/ multiple times and it's alway sthe same issue

Are there any other location that need to be cleaned?

**Comment by adrianinsaval** [comment]
this is an issue in FreeCAD itself not the bundle, please refer to https://github.com/FreeCAD/FreeCAD/issues/12199
