### ISSUE TITLE
External geometry is not removed

### ISSUE THREAD

**Issue by kaiwas** [FreeCAD/FreeCAD-Bundle#215]
In version 0.22 (dated March 11, 2024), external geometry is not deleted when making multiple selections.
But it can be removed by selecting each element with a single click.
However, not all selected items are displayed in the selection filter.
Video demonstration.

https://github.com/FreeCAD/FreeCAD-Bundle/assets/32273833/55ac7c2f-8c97-47bb-9fb8-03f0ea742c3c

**Comment by maxwxyz** [comment]
closed in favor of https://github.com/FreeCAD/FreeCAD/issues/13009
