### ISSUE TITLE
Assembly4 stopped working on recent daily updates 'QtCore' is not defined

### ISSUE THREAD

**Issue by Eksterminator** [FreeCAD/FreeCAD-Bundle#222]
![image](https://github.com/FreeCAD/FreeCAD-Bundle/assets/13043178/bb2e3700-f6c9-42c1-a335-0e68c0c26b8c)
19:55:36  name 'QtCore' is not defined
19:55:36  Traceback (most recent call last):
  File "C:\Users\Me\AppData\Roaming\FreeCAD\Mod\Assembly4\.\InitGui.py", line 100, in Initialize
    msgBox.setWindowFlags( QtCore.Qt.WindowStaysOnTopHint )
                           ^^^^^^

**Comment by adrianinsaval** [comment]
This is an assembyl4 issue, report it there. It's not importing QtCore
https://github.com/Zolko-123/FreeCAD_Assembly4/blob/224d9e2de4e3b43ed9f07b635537dea7159f9fec/InitGui.py#L93-L104

either way it seems he's unwilling to update his workbench to work with the latests versions of freecad so you won't get far there
