### ISSUE TITLE
Sketcher constraint cannot be deleted or selected

### ISSUE THREAD

**Issue by ofpkubi** [FreeCAD/FreeCAD-Bundle#225]
Hi,

There seems to be a fault selecting / deleting sketcher constraints in latest bundle appimage.
FreeCAD_weekly-builds-36996-conda-Linux-x86_64-py311.AppImage - works
FreeCAD_weekly-builds-37213-conda-Linux-x86_64-py311.AppImage - faulty

How to reproduce:
- Create new document
- Create a sketch
- Draw anything simple (line, circle etc.) with some constraints (e.g., endpoint on axis)
- Fault 1: Try to select the constraint on the viewport by clicking on its icon. --> cannot select
- Fault 2: Select constraint from the constraint list. Selected in the list, but not in the viewport.
- Fault 3: Press <Del> or richt-click / Delete nothing happens.

Once I've got the following message: "Delete: Selection not restricted to one sketch and its subelements"

**Comment by caco3** [comment]
IMO there seem to be deletion issues since a while.
Since weeks I am unable to delete any constraints in the sketcher.
