### ISSUE TITLE
Version before TNP.

### ISSUE THREAD

**Issue by leoheck** [FreeCAD/FreeCAD-Bundle#231]
Hey guys, could you share a version (AppImage) that works before the TNP starts to be fixed?
There are too many issues happening after this.

**Comment by FEA-eng** [comment]
You should report any issues that you encounter (and that haven't been reported yet) so they can be fixed. The current TNP phase (testing and bug fixing) is meant for that.

**Comment by leoheck** [comment]
Sorry dude, I think you are not ok or did not understand or read the issue here. The issue here is asking for a valid version that works before this TPN shit started to be fixed since this introduced tons of bugs.

**Comment by FEA-eng** [comment]
If something is not ok, it’s definitely your approach.

Old weekly builds are not archived. I suggested reporting bugs because it’s a big problem that many FreeCAD users only complain about some unspecified issues but don’t want to report them so that they can be fixed.

**Comment by leoheck** [comment]
lol
