### ISSUE TITLE
Settings window freezes

### ISSUE THREAD

**Issue by sneakythomas** [FreeCAD/FreeCAD-Bundle#234]
After starting the program, the Settings window freezes. You can only select various options after approx. 1 minute. It occurs in all versions (stable, weekly).

**Comment by sneakythomas** [comment]
I use FreeCAD under Win 11.

**Comment by maxwxyz** [comment]
@sneakythomas please create the issues in the FreeCAD repository https://github.com/FreeCAD/FreeCAD/issues
