### ISSUE TITLE
Broken icon on Gnome Shell

### ISSUE THREAD

**Issue by leoheck** [FreeCAD/FreeCAD-Bundle#237]
The icon is broken on Gnome Shell, using Freecad `0.22.0dev.37543`.

This was fixed in the past, now it is broken again. 
There are 2 places where it is missing, on the bottom of the window and the favorites bar.
![image](https://github.com/FreeCAD/FreeCAD-Bundle/assets/1277920/ba66d330-18ac-4560-ace4-e2213d8c94a1)

Here the icon appears. I am not sure it is the right one, but there is something at least.
![image](https://github.com/FreeCAD/FreeCAD-Bundle/assets/1277920/b350cf80-ddbb-48fc-8a04-a30d764e67b5)

This one is what they are using on Discord.
![image](https://github.com/FreeCAD/FreeCAD-Bundle/assets/1277920/8dd7800d-6740-4400-8c88-52a50196be36)

```
OS: Ubuntu 24.04 LTS (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37543 (Git) AppImage
Build type: Release
Branch: main
Hash: 3eb45b045cdda9d5bfe11baba2567a1df90f064c
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
```

**Comment by GAZ082** [comment]
In the discord has been talks of having a different DEV icon just to make sure you start the right version of the program. But I agree it should be displayed instead of the cog.

**Comment by maxwxyz** [comment]
@adrianinsaval are there different locations where the separate image was used which need to point to the default icon?

**Comment by leoheck** [comment]
in the past I have fixed this.. it needs the icon in some specific sizes I guess...

**Comment by leoheck** [comment]
The latest version does not have this broken. However, the blue icon has gone... 

![image](https://github.com/FreeCAD/FreeCAD-Bundle/assets/1277920/dc8140c3-a2f0-4700-b83c-4efb45805969)

```
OS: Ubuntu 24.04 LTS (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37668 (Git) AppImage
Build type: Release
Branch: main
Hash: ea68c5e88cdc80044ede482f6ad908820f4c1c82
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Installed mods: 
  * POV-Ray-Rendering
  * Assembly4 0.50.12
  * sheetmetal 0.4.17
  * InventorLoader 1.4.0
  * ose-piping
  * fasteners 0.5.21
  * asm4_disable_version_check_popup
  * OpenDark 2024.3.13
  * ProDarkThemePreferencePack 1.0.0
  * Render 2024.6.5
  * OpticsWorkbench 1.0.17
  * lattice2 1.0.0
  * kicadStepUpMod
```

**Comment by maxwxyz** [comment]
is it also fixed in the app switcher? 
The icon change was intentional.

**Comment by leoheck** [comment]
Yes, it is fixed there too. I am going to close this for now.

**Comment by leoheck** [comment]
![image](https://github.com/FreeCAD/FreeCAD-Bundle/assets/1277920/86a0de30-7d42-4748-95c0-667feafafb59)
