### ISSUE TITLE
Fix for FreeCAD dev silently closing

### ISSUE THREAD

**Issue by casterle** [FreeCAD/FreeCAD-Bundle#246]
For the last few dev releases, FreeCAD has been silently closing. I finally found time to look into the problem. Here's what fixed the issue (for me).

In User.cfg, I deleted the indicated lines. 

```
        <FCParamGroup Name="DockWindows">
==>       <FCParamGroup Name="TaskWatcher">
==>         <FCBool Name="Enabled" Value="1"/>
==>       </FCParamGroup>
        </FCParamGroup>

```

**Comment by maxwxyz** [comment]
Is this still an issue in the latest weekly?
If so please create an issue (if there is not already an existing one) here https://github.com/FreeCAD/FreeCAD/issues
