### ISSUE TITLE
Weekly builds file naming no longer following legend.

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [FreeCAD/FreeCAD-Bundle#250]
The legend indicates that the weekly builds include a date in the filename:
![image](https://github.com/FreeCAD/FreeCAD-Bundle/assets/38865330/ad7705cf-609e-4c59-b782-2dd3de80dd5d)

However, recent builds do not include a date:
![image](https://github.com/FreeCAD/FreeCAD-Bundle/assets/38865330/be62947e-c8cc-4c65-92b5-6ff400f8ee4f)

Is this an intentional change, or an oversight in the release process? This filename is used to generate the version for the Chocolatey package, so format changes break the automation.

**Comment by maxwxyz** [comment]
@adrianinsaval FYI

**Comment by adrianinsaval** [comment]
The change was made on purpose because the date of the upload can now be seen on github, so it gave no useful information just making it unnecessarily long. I'll try my best to keep the format stable from now on.

**Comment by adrianinsaval** [comment]
Since it looks like they've fixed it on the Chocolatey side I will close this issue as changing it back will just create problems again
