### ISSUE TITLE
Beta flatpak contains the release version (0.21)

### ISSUE THREAD

**Issue by aasseman** [FreeCAD/FreeCAD-Bundle#254]
I tried installing the dev version of FreeCAD using those instructions (`flathub-beta`) : https://wiki.freecad.org/Flatpak
But it installs the same version as the regular flatpak (0.21.2).

**Comment by kotovasia5120** [comment]
![image](https://github.com/FreeCAD/FreeCAD-Bundle/assets/76496357/d26692f0-bd2c-4562-a003-5eefc16c755a)
https://wiki.freecad.org/Installing_on_Linux

**Comment by aasseman** [comment]
> ![image](https://private-user-images.githubusercontent.com/76496357/341238420-d26692f0-bd2c-4562-a003-5eefc16c755a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4OTk3MzAsIm5iZiI6MTcxODg5OTQzMCwicGF0aCI6Ii83NjQ5NjM1Ny8zNDEyMzg0MjAtZDI2NjkyZjAtYmQyYy00NTYyLWEwMDMtNWVlZmMxNmM3NTVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDE2MDM1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjNjNiN2YzMTQ1YjhhMWE4OWQ0OWY0MmI5N2Y2MjM4NTE1ZWZmZTgyOTY0NDIyMTU4ODhmY2Y5YjU4Yjk0M2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s4s-2fneNN_g9u_m3JXHRPcL0NyU928C644nb8X-2tI) https://wiki.freecad.org/Installing_on_Linux Use [PPA](https://wiki.freecad.org/Installing_on_Linux#Development_PPA_.28Daily.29) daily repository, [AppImages](https://wiki.freecad.org/AppImage), [Ubuntu Snaps](https://wiki.freecad.org/Ubuntu_Snap).

I think you didn't understand what I mean. Here's a screenshot of https://wiki.freecad.org/Flatpak:
![image](https://github.com/FreeCAD/FreeCAD-Bundle/assets/33075224/c7363707-bf76-4ecc-94da-df545c3f2e22)

If you follow that, you get the normal release version, not the dev version.

**Comment by kinghat** [comment]
i know that beta != to dev but afaik there arent any beta versions of freecad being released. is it possible to get the freecad weeklies building to the flatpak beta repo? i havent been able to use the appimages for a few months because of freezing: 

https://github.com/FreeCAD/FreeCAD/issues/15026
https://github.com/FreeCAD/FreeCAD/issues/14287
https://forum.freecad.org/viewtopic.php?t=87325

**Comment by adrianinsaval** [comment]
beta flatpak is now at 1.0rc2 but was renamed to org.freecad.FreeCAD
