### ISSUE TITLE
Revolution up to face without function

### ISSUE THREAD

**Issue by TimTwix** [FreeCAD/FreeCAD-Bundle#257]
Hello,

if I create a datum and a simple sketch and choose revolution "up to face" nothing is changing. Freecad seems to take still the value from dimension.

![Bildschirmfoto vom 2024-06-21 18-07-38](https://github.com/FreeCAD/FreeCAD-Bundle/assets/173486014/93fe304f-03e9-4f02-bd39-14f2883f7141)

![Bildschirmfoto vom 2024-06-21 18-08-31](https://github.com/FreeCAD/FreeCAD-Bundle/assets/173486014/da40ad4d-e927-46f9-a0a8-7841c5953fe2)

**Comment by maxwxyz** [comment]
Is this still an issue?
If so please create an issue here https://github.com/FreeCAD/FreeCAD/issues
