### ISSUE TITLE
Wierd issue with the GUI maybe on AppImage only.

### ISSUE THREAD

**Issue by leoheck** [FreeCAD/FreeCAD-Bundle#259]
Wierd issue with the GUI.
Some elements are not being rendered nicely. 

Please, can you see this comment here:
https://github.com/shaise/FreeCAD_SheetMetal/issues/346#issuecomment-2194820138

Perhaps it is a problem with the AppImage, can someone else check this buy installing the SheetMetal workbench and launching the `Add Base Shape`. The following blue icon: ![image](https://github.com/FreeCAD/FreeCAD-Bundle/assets/1277920/3260beac-bca3-4442-987e-edaf0444689a)

Using 
```
OS: Ubuntu 24.04 LTS (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37898 (Git) AppImage
Build type: Release
Branch: main
Hash: 308013fb975ec3bf0dc5cb616ef76a4095e71cc5
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Installed mods: 
  * POV-Ray-Rendering
  * Assembly4 0.50.12
  * InventorLoader 1.4.0
  * ose-piping
  * SheetMetal 0.4.20
  * fasteners 0.5.24
  * asm4_disable_version_check_popup
  * OpenDark 2024.3.13
  * ProDarkThemePreferencePack 1.0.0
  * Render 2024.6.5
  * OpticsWorkbench 1.0.18
  * lattice2 1.0.0
  * kicadStepUpMod
```

**Comment by adrianinsaval** [comment]
looking at the sheetmetal issue it seems this was rather a bug in opendark
