### ISSUE TITLE
Pad: Shape must be a wire, edge or compound. Something else was supplied.

### ISSUE THREAD

**Issue by indianatechguy** [FreeCAD/FreeCAD-Bundle#272]
I am receiving the following error when I attempt to pad a slot with a square sketched in the center of it in version .0.22.0dev rev 38334 on Windows 11 23H2.

"Pad: Shape must be a wire, edge or compound. Something else was supplied."

I saved the file and it successfully created the pad in FreeCAD version 0.21.1.

<img width="886" alt="Pad Error" src="https://github.com/user-attachments/assets/1ab70cea-cc4d-4a20-8bd3-8f8761d85781">

**Comment by maxwxyz** [comment]
I guess it is because of the additional point in the center. Try converting this point to a construction geo point.
If there is still an issue, please use the FreeCAD repository: https://github.com/FreeCAD/FreeCAD
