### ISSUE TITLE
Font colour selection in Spreadsheets only works in the FreeCAD Classic theme.

### ISSUE THREAD

**Issue by JDMils** [FreeCAD/FreeCAD-Bundle#275]
With FreeCAD Classic theme selected and applied, in Spreadsheet, you can use the cell colour toolbar buttons to change the selected cell font and background colour- no problem here.

With FreeCAD Light theme selected and applied, in Spreadsheet, you can use the cell colour toolbar buttons to only change the selected cell background colour however the cell font colour toolbar button has no effect on the cell's font colour. Even trying to change the font colour using <right-click> | Properties | Color, change White to any other colour, the cell's font colour does not change.

With FreeCAD Dark theme selected and applied, in Spreadsheet, you can use the cell colour toolbar buttons to only change the selected cell background colour however the cell font colour toolbar button has no effect on the cell's font colour. Even trying to change the font colour using <right-click> | Properties | Color, change White to any other colour, the cell's font colour does not change.

While using the FreeCAD Dark theme, the current cell colours are:
Font: White
Background: Green

I then change the font colour to Yellow however nothing changes. I then change the theme to FreeCAD Light and the cell's font colour is now black. I then change the theme to FreeCAD Classic and the cell's font colour is now Yellow. I change the cell font to White and the cell shows a white font. I change the cell font to Magenta and change the theme to FreeCAD Dark however the cell font is now White.

My forum post:
https://forum.freecad.org/viewtopic.php?style=3&p=773564#p773564

`OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38314 (Git)
Build type: Release
Branch: main
Hash: 3fa339e9eb71d34542e463b3f4581857a9e696fb
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/Australia (en_AU)
Installed mods: 
  * Gridfinity 0.5.0
`

**Comment by luzpaz** [comment]
Wrong repo. Please use https://github.com/FreeCAD/FreeCAD/
Also, see https://github.com/FreeCAD/FreeCAD/issues/8168
