### ISSUE TITLE
All Sketcher units switch from inches to mm after applying a Pad operation with "Ignore project unit system and use default" selected

### ISSUE THREAD

**Issue by arena-** [FreeCAD/FreeCAD-Bundle#276]
In short, the "Ignore project unit system and use default" option results in unexpected behavior.

In a new document, after setting units to "Imperial Decimal (inches, pounds)" via the Preferences, the sketch dimensions appear still appear in mm. Go back to Preferences and select "Ignore project unit system and use default" - and now inches are displayed. Apply a Pad operation, it prompts for "10 mm", type in "1 inch". Return to the sketch, all the dimensions now appear in mm.   

Steps to replicate:
1. Open FreeCAD
2. Create a New document
3. Go to Edit->Preferences
4. Default unit system -> from Standard to "Imperial Decimal"
5. Create a Body and Sketch
6. Centered Rectangle with 2 dimensions - they appear in mm
7. Go to Edit->Preferences - tick "Ignore project unit system and use default"
8. Dimensions now appear in inches
9. Go to Pad the Sketch
10. Replace the default "10 mm" with "1 inch"
11. Return to the Sketch
12. Observe the Sketch dimensions are now in mm

Interestingly, if you follow these steps, you do not encounter a problem:
1. Open FreeCAD
2. Go to Edit->Preferences
3.  Default unit system -> from Standard to "Imperial Decimal"
4. New Document
5. etc. .. all works in inches as expected

Creating a New document AFTER changing the Preferences prevents this problem, or going to File-> Document information and changing it from there seems to work.

Suggestions: 
- Have it so changing the default unit system after creating a new document results in the new document applying those settings straight away.
- Have the option to change the unit system for the document you are working on under Edit->Preferences as well as File->Document information, for clarity 

Thank you

OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38334 (Git)
Build type: Release
Branch: main
Hash: 61c964caa9a7e5bbc7a8d5f7d8914505d365113e
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/Australia (en_AU)
Installed mods: 
  * fasteners 0.5.24

**Comment by luzpaz** [comment]
Thank you for the bug report however  you've posted this to the wrong repo.
The correct repo is https://github.comFreeCAD/FreeCAD

Please check the open issues for 'units' based bugs (which is what you're reporting about) in https://github.com/FreeCAD/FreeCAD/issues?q=is%3Aopen+is%3Aissue+label%3A%22Topic%3A+Units%22
