### ISSUE TITLE
Mesh Workbench: Quasi structured quad not working

### ISSUE THREAD

**Issue by jintat87** [FreeCAD/FreeCAD-Bundle#277]
Hi,

I'm trying on the FreeCAD_weekly-builds-0.22.0dev-38385.

In Mesh Workbench, when I use Tesselate shape to create mesh from shape with Gmsh using Quasi Structured Quad, it produces no result.

I have tried the gmsh that comes with the package in bin folder, as well as latest gmsh-4.13.1. Both same without result.

Hope you can look into this. Thanks.

**Comment by luzpaz** [comment]
Full About info please. Also is this Appimage (packaging) related or just FreeCAD itself ?

**Comment by jintat87** [comment]
it's regarding this latest fix weekly build [#15661](https://github.com/FreeCAD/FreeCAD/pull/15661
)
The Quasi-structured Quad added to Mesh wb but there's no output.
![image](https://github.com/user-attachments/assets/37a85e4b-df3e-4f65-914c-5955250b92c1)

**Comment by luzpaz** [comment]
@jintat87 is this an appimage related bug or is it a bug in FreeCAD ?

**Comment by maxwxyz** [comment]
If this issue is still existing, please open it in the FreeCAD repo if there are no similar issues/duplicates.
@FEA-eng FYI
