### ISSUE TITLE
Problems creating and array of parts with draft workbench

### ISSUE THREAD

**Issue by Achu69** [FreeCAD/FreeCAD-Bundle#278]
Draft Array not working with parts. I am trying to create a simple array of a part (cylinder) in a 2 x 2 configuration but this is not shown on screen after clicking ok

OS: macOS 14.5
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38385 (Git)
Build type: Release
Branch: main
Hash: 58241e027e7187a1ecaeeb75668ef9a497437c68
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, and OCC 7.7.2
Locale: C/Default (C)
Installed mods: 
  * Gridfinity 0.3.0
  * A2plus 0.4.64
  * Curves: 0.6.29

**Comment by luzpaz** [comment]
This isn't the main FreeCAD repository bugtracker. This repository is for packaging FreeCAD. Can you open a ticket on the main repo please? https://github.com/FreeCAD/FreeCAD
