### ISSUE TITLE
Update installers to register new FreeCAD logo for FCStd / FCMacro in different OS

### ISSUE THREAD

**Issue by maxwxyz** [FreeCAD/FreeCAD-Bundle#281]
@adrianinsaval you've mentioned it yesterday, I hope I've captured it correctly:
Update installers to register new FreeCAD logo for FCStd / FCMacro in different OS

**Comment by adrianinsaval** [comment]
I'm not entirely sure what's the mechanism by which the logo gets added to the preview on windows, I don't know if it's a feature from windows itself or if it's from our thumbnail provider.

I don't even know how to compile the dll for the thumbnails actually. @chennes do you know how to do that?

**Comment by maxwxyz** [comment]
Can this be closed or was there any feedback from the RCs that this is not working?

**Comment by adrianinsaval** [comment]
From my testing the overlayed icon seems to be added by windows itself based on what program is configured to open the file so there's no action needed
