### ISSUE TITLE
FreeCAD Weekly Build 38429

### ISSUE THREAD

**Issue by Bladevane** [FreeCAD/FreeCAD-Bundle#282]
Something has gone astray with Polar Patterns between Weekly Build 38419 and 38429. The former appears fine but the latter does some weird stuff.

**Comment by chennes** [comment]
Probably fixed by https://github.com/FreeCAD/FreeCAD/pull/15845

**Comment by maxwxyz** [comment]
@Bladevane I'll close this. If the issue still exists in tomorrows weekly, please open an issue in the FreeCAD repo: https://github.com/FreeCAD/FreeCAD

**Comment by Bladevane** [comment]
Max,

 

Thanks for your response. I’ve just checked Weekly Build 38459 and Polar Pattern still gives a problem. I have raised it as an issue as you recommend.

 

Regards,

 

Glyn Walton.
