### ISSUE TITLE
Minum Mac OS change from last week?

### ISSUE THREAD

**Issue by longrackslabs** [FreeCAD/FreeCAD-Bundle#292]
Did the minimum OS version change from this week from last? I have Mac OS version 12.7.5 (monterey), last weeks x86_64 runs fine, this week it is not runnable/installable. I hope this is mistake this week! 

![image](https://github.com/user-attachments/assets/fa09ecf0-1289-4901-9ca1-0aa1bb5af9e6)
![image](https://github.com/user-attachments/assets/048fd888-756d-4092-83d9-64eda1c2d0d3)

**Comment by luzpaz** [comment]
Looks like it was broken by #290
