### ISSUE TITLE
[FEATURE REQUEST] Independent project/view tabs

### ISSUE THREAD

**Issue by samohd** [FreeCAD/FreeCAD-Bundle#295]
Ability to have independent tabs. For example, to be able to select tab/document 1 and go into Sketcher. Then select tab/document 2 and go into Sketcher. Then going back and forth between the two tabs/documents, you can compare things done within Sketcher.

Similarly you should also be able to open separate tabs for multiple sketches within the same project. The same programming implementation works for both of these uses.

Programmatically this is fairly easy to do and super beneficial. The first example is particularly useful for beginners, like myself, to compare other sample projects to see how things are done, and jump back and forth to implement in one's own document.

**Comment by luzpaz** [comment]
Wrong place to post. The main bugtracker is at https://github.com/FreeCAD/FreeCAD/issues/  
You;re issue is already a ticket: https://github.com/FreeCAD/FreeCAD/issues/11914
