### ISSUE TITLE
Add github issue template to curb the amount of tickets that are meant for FreeCAD/FreeCAD

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-Bundle#299]
@maxwxyz this might be the better solution because people are still ignoring the pinned issue

**Comment by maxwxyz** [comment]
Yes but I think they will still ignore it, same as the checkbox 'I have searched for similar issues'

**Comment by luzpaz** [comment]
I'll make a PR and we can discuss strategies

**Comment by JohnOCFII** [comment]
With people blindly following links -- some that go back and forth between the `FreeCAD` and `FreeCAD-Bundle` repositories -- anything to clearly show that **THIS** isn't the main FreeCAD repository would be useful.

**Comment by maxwxyz** [comment]
What if we do not allow issues here and instead the packaging related issues are reported in the main repo? I mean there are already some with the tag.

**Comment by luzpaz** [comment]
Or the opposite, move all the packaging issues here ?

**Comment by JohnOCFII** [comment]
> Or the opposite, move all the packaging issues here ?

Or -- does this need to be a separate repo?

**Comment by luzpaz** [comment]
> Or -- does this need to be a separate repo?  

Separate from what? This repo is dedicated to building and packaging FC. What would you propose for a new repo that is different than this one ?

**Comment by JohnOCFII** [comment]
> Edit: oh, are you proposing merging this repo back into FreeCAD/FreeCAD ?

Yes, that was my question -- is the hassle with issues showing up in the wrong respository enough of a reason to try to handle the current `FreeCAD-Bundle` Repository activities as just part of the main FreeCAD repository.

And it was truly at the question stage -- I don't know near enough about the mechanics to know if this is a bad idea or not.
