### ISSUE TITLE
1.0RC is being released as 1.0.0 and this will cause confusion.

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-Bundle#305]
Link: https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/1.0rc1

![Screenshot_20240911_115851](https://github.com/user-attachments/assets/413c404d-06eb-47f5-a36d-5536f3e52705)

Is this due to some technical limitation or just an oversight ?

TIA for your attention @adrianinsaval

**Comment by oursland** [comment]
The issue is narrowed down to how [`get_freecad_version.py`](https://github.com/FreeCAD/FreeCAD-Bundle/blob/main/conda/scripts/get_freecad_version.py) determines the version information.

**Comment by oursland** [comment]
@chennes Is this supposed to be `FreeCAD_1.0.0RC1-...` or `FreeCAD_1.0.0_RC1-...`?

**Comment by chennes** [comment]
I don't have a preference.

**Comment by oursland** [comment]
I'll follow the convention in the About box:

![image](https://github.com/user-attachments/assets/adfdac8e-de27-4ede-9a50-94e25b6424b3)

`FreeCAD_1.0.0RC1-...`
