### ISSUE TITLE
Due to RC release perhaps publishing nightlies will help get us to 1.0 faster ?

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-Bundle#307]
I've been thinking about this a bunch and finally i saw [this comment](https://github.com/FreeCAD/FreeCAD-Bundle/issues/304#issuecomment-2344721092) and decided to make the request.

We could either make a nightly tag or just increase the frequency of the weekly tag to publish builds every day ?

**Comment by adrianinsaval** [comment]
ugh I should have answered here. Made some long answers on the other issue

@oursland probably a better idea to continue that conversation here?

**Comment by oursland** [comment]
@adrianinsaval 's [response](https://github.com/FreeCAD/FreeCAD-Bundle/issues/304#issuecomment-2345075515) explains that doing so would block the CI runners for 2.5 hours (or longer) and prevent regular CI tasks.
