### ISSUE TITLE
Resize a STL using resize in draft create a blank clone

### ISSUE THREAD

**Issue by eagabriel** [FreeCAD/FreeCAD-Bundle#313]
Import a STL, go to draft, choose resize, resize it like 1,1 the STL will be resize at least as a preview, is it possible to see it resized, but when you apply a blank clone is created.
Using FreeCAD_weekly-builds-38843-conda-Windows-x86_64-py311
The same works in 0.21

![image](https://github.com/user-attachments/assets/fc84c0b5-580b-45b8-8b97-fdeba02bb580)

**Comment by FreeWilly2022** [comment]
As it says on the top page, please do NOT open general issues for FreeCAD here. This is only for issues with the bundle specifically.
Instead use the main FreeCAD repository https://github.com/FreeCAD/FreeCAD/issues

**Comment by eagabriel** [comment]
Oh sorry for that, I thought that I was in the right place, tks for advise.
