### ISSUE TITLE
AutoUpdate Feature - Add Operation Details + RC1 erroneously auto-updates to 0.21.2

### ISSUE THREAD

**Issue by LB45440078L** [FreeCAD/FreeCAD-Bundle#317]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When doing an automatic update of the app, using an AppImage release, there's no sort of progress or detail of what's happening during it.
On slow computers, an update can take several minutes, and since the app gets stuck and doesn't have a loading bar or any step, one may be easily prone to close it or unable to know if installation steps are proceeding successfully.

### Full version info

```shell
OS: CachyOS (GNOME/gnome)
Word size of FreeCAD: 64-bit
Version: 1.0.0RC1.38642 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 1.0rc1)
Hash: 60a251354e203bdb924e2190fb9f5e18b48d7362
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United Kingdom (en_GB)
Installed mods: 
  * Render 2024.8.4
```

### Subproject(s) affected?

None

### Anything else?

Tips for implementation: Add some sort of progress bar, or some text that indicates ongoing operations and eventual errors.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adrianinsaval** [comment]
rc3 and rc4 will not update to stable releases but not to higher rcs either, that's the best I can do at the moment. Details seem to be shown properly for everyone else so I'll close this issue
