### ISSUE TITLE
Workbench tabs not changing workbench toolbars correctly

### ISSUE THREAD

**Issue by bman2000** [FreeCAD/FreeCAD-Bundle#319]
I am using the most recent weekly build and I find that when you are using the tab function, for the workbenches, and switch between work benches, the workbench toolbars do not change reliably. This is not a problem if you use the workbench selector from the drop down menu.

**Comment by adrianinsaval** [comment]
https://github.com/FreeCAD/FreeCAD-Bundle/issues/285
