### ISSUE TITLE
Tree View font sixe not persisted...

### ISSUE THREAD

**Issue by CIKoolK** [FreeCAD/FreeCAD-Bundle#343]
I have found that the Edit|Preferences|Display|Advanced Tree View font setting while dynamically effective, is not persisted between sessions:
1. Upon initial startup it is set and displayed as 10 pt.;
2. I adjust it to 13 pt., click Apply, and it is applied;
3. Shut down and restart, it is shown as 13 pt. in the Preferences, but displayed in 10 pt.

![FCTreeView-00](https://github.com/user-attachments/assets/cd5a9dd4-460b-4a37-924c-c5cd6cec4327)

![FCTreeView-01](https://github.com/user-attachments/assets/a2996938-da67-4a4b-9a8a-d8929a5d1aa0)

![FCTreeView-02](https://github.com/user-attachments/assets/805d7fdc-f262-48ff-9367-d95694446f84)

As I have reported previously, I have significant vision problems making this sort of thing bothersome...

**Comment by CIKoolK** [comment]
Still not working in build 39503...

**Comment by Syres916** [comment]
@CIKoolK hopefully you will see the fix in the next week or two but in future please log application issues at https://github.com/FreeCAD/FreeCAD/issues this repository is only for the actual _packaging_ not the _code_.

**Comment by CIKoolK** [comment]
Will do, thank you!
