### ISSUE TITLE
macOS arm64 "FreeCAD-1.1.0dev39315" is damaged and can't be opened.

### ISSUE THREAD

**Issue by winstonford** [FreeCAD/FreeCAD-Bundle#344]
**Describe the bug**
When attempting to open the app on macOS arm64, I get a dialogue "FreeCAD-1.1.0dev39315" is damaged and can't be opened. You should move it to the Trash."

I have gotten this same error on the last two weeklies: 39240, and 39215.  However, 1.0.0 and all the release candidates opened normally without problems.

On macOS x86, I *am* able to open 1.1.0dev39315, 39240, and 39215 normally, with no problems.

**To Reproduce**
1. Download weekly
2. Double click .dmg
3. Copy app to /Applications
4. Double click on app, or right click open app.

**Screenshots**

<img width="372" alt="freecad-damaged" src="https://github.com/user-attachments/assets/ab388ad7-c345-489c-a184-4943a69f8828">

**Additional context**

<img width="392" alt="Screenshot 2024-11-25 at 8 14 18 PM" src="https://github.com/user-attachments/assets/c86116e1-08ff-4d26-b242-9301530acbfd">

**Comment by oursland** [comment]
The weekly builds are not signed.  When downloaded from your browser, a `quarantine` flag is added to the file.  To remove the `quarantine` run the following command:

`xattr -cr /Applications/FreeCAD.app`

**Comment by winstonford** [comment]
Great, all opening normally.  Thanks for the tip.  I suppose the tip could be added to a readme file in the dmg.
