### ISSUE TITLE
Daily PPA package ships 2-weeks-old build

### ISSUE THREAD

**Issue by furgo16** [FreeCAD/FreeCAD-Bundle#354]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The current package in the FreeCAD daily PPA seems to include an old build instead of the daily one. The FreeCAD About info reports it includes a snapshot of the [735a07678d8682d5936906298ed61cb2efd0eb66](https://github.com/FreeCAD/FreeCAD/commit/735a07678d8682d5936906298ed61cb2efd0eb66) git hash, which is two weeks old. 

Coincidentally, it's the same date as the builds were failing recently, as reported at https://github.com/FreeCAD/FreeCAD-Bundle/issues/348. Perhaps related?

This is the Debian package version currently available in the PPA where the issue is reproduceable, from yesterday.

```
$ apt show freecad-daily

Package: freecad-daily
Version: 1.1~pre1~202412101233~ubuntu24.04.1
Priority: optional
Section: science
Maintainer: Debian Science Maintainers <debian-science-maintainers@lists.alioth.debian.org>
Installed-Size: 25,6 kB
Depends: freecad-daily-python3
Recommends: calculix-ccx, graphviz, git
Breaks: freecad-daily (<< 0.22)
Replaces: freecad-daily (<< 0.22)
Download-Size: 6.864 B
APT-Manual-Installed: yes
APT-Sources: https://ppa.launchpadcontent.net/freecad-maintainers/freecad-daily/ubuntu noble/main amd64 Packages
Description: Extensible Open Source CAx program
 FreeCAD is an Open Source CAx RAD based on OpenCasCade, Qt and Python.
 It features some key concepts like macro recording, workbenches, ability
 to run as a server and dynamically loadable application extensions and
 it is designed to be platform independent.
 .
 Currently, FreeCAD can import and display CAD models in IGES, STEP, and
 BRep formats and meshes in STL, BMS, AST and Wavefront OBJ formats.
 Editing and modeling features are currently somewhat limited.
 .
 This is a metapackage of FreeCAD component packages.
```

### Full version info

```shell
OS: Ubuntu 24.04.1 LTS (ubuntu:GNOME/ubuntu/xcb)
Architecture: x86_64
Version: 1.1.0dev.39358 (Git)
Build type: Release
Branch: main
Hash: 735a07678d8682d5936906298ed61cb2efd0eb66
Python 3.12.3, Qt 5.15.13, Coin 4.0.2, Vtk 9.1.0, OCC 7.8.1
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Installed mods: 
  * OpenTheme 2024.9.1
  * WikiPropertiesGenerator.FCMacro
  * fasteners 0.5.30
```

### Subproject(s) affected?

Other (specify in description)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by furgo16** [comment]
Today's package has a higher Debian package version, but its contents are still stuck at git's  https://github.com/FreeCAD/FreeCAD/commit/735a07678d8682d5936906298ed61cb2efd0eb66 hash.

```
$ apt show freecad-daily

Package: freecad-daily
Version: 1.1~pre1~202412111233~ubuntu24.04.1
Priority: optional
Section: science
Maintainer: Debian Science Maintainers <debian-science-maintainers@lists.alioth.debian.org>
Installed-Size: 25,6 kB
Depends: freecad-daily-python3
Recommends: calculix-ccx, graphviz, git
Breaks: freecad-daily (<< 0.22)
Replaces: freecad-daily (<< 0.22)
Download-Size: 6.858 B
APT-Manual-Installed: yes
APT-Sources: https://ppa.launchpadcontent.net/freecad-maintainers/freecad-daily/ubuntu noble/main amd64 Packages
Description: Extensible Open Source CAx program
 FreeCAD is an Open Source CAx RAD based on OpenCasCade, Qt and Python.
 It features some key concepts like macro recording, workbenches, ability
 to run as a server and dynamically loadable application extensions and
 it is designed to be platform independent.
 .
 Currently, FreeCAD can import and display CAD models in IGES, STEP, and
 BRep formats and meshes in STL, BMS, AST and Wavefront OBJ formats.
 Editing and modeling features are currently somewhat limited.
 .
 This is a metapackage of FreeCAD component packages.
```

```
OS: Ubuntu 24.04.1 LTS (ubuntu:GNOME/ubuntu/xcb)
Architecture: x86_64
Version: 1.1.0dev.39358 (Git)
Build type: Release
Branch: main
Hash: 735a07678d8682d5936906298ed61cb2efd0eb66
Python 3.12.3, Qt 5.15.13, Coin 4.0.2, Vtk 9.1.0, OCC 7.8.1
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Installed mods: 
  * OpenTheme 2024.9.1
  * WikiPropertiesGenerator.FCMacro
  * fasteners 0.5.30
```

**Comment by mfraser** [comment]
Another related issue is that the package libfreecad-daily-python3-1.1 which replaces libfreecad-daily-python3-0.22 doesn't have any dependencies.

```
Package: libfreecad-daily-python3-0.22
Version: 0.22~pre1~202412072316~ubuntu22.04.1
Priority: optional
Section: libs
Source: freecad-daily
Maintainer: Debian Science Maintainers <debian-science-maintainers@lists.alioth.debian.org>
Installed-Size: 126 MB
Depends: libboost-filesystem1.74.0 (>= 1.74.0), libboost-program-options1.74.0 (>= 1.74.0), libboost-regex1.74.0-icu70, libboost-thread1.74.0 (>= 1.74.0), libc6 (>= 2.34), libcoin80c (>= 4.0.0+ds), libfmt8 (>= 8.1.1+ds1), libfreetype6 (>= 2.2.1), libgcc-s1 (>= 3.4), libgl1, libgomp1 (>= 6), libmedc11, libocct-data-exchange-7.8 (>= 1:7.8.1+dfsg1), libocct-foundation-7.8 (>= 1:7.8.1+dfsg1), libocct-modeling-algorithms-7.8 (>= 1:7.8.1+dfsg1), libocct-modeling-data-7.8 (>= 1:7.8.1+dfsg1), libocct-ocaf-7.8 (>= 1:7.8.1+dfsg1), libocct-visualization-7.8 (>= 1:7.8.1+dfsg1), libpyside2-py3-5.15 (>= 5.15.2), libpython3.10 (>= 3.10.0), libqt5concurrent5 (>= 5.6.0~rc), libqt5core5a (>= 5.15.1), libqt5gui5 (>= 5.14.1) | libqt5gui5-gles (>= 5.14.1), libqt5network5 (>= 5.15.1), libqt5printsupport5 (>= 5.10.0), libqt5svg5 (>= 5.6.0~beta), libqt5widgets5 (>= 5.15.1), libqt5xml5 (>= 5.0.2), libshiboken2-py3-5.15 (>= 5.15.2), libspnav0 (>= 0.2.2), libstdc++6 (>= 11), libtbb12 (>= 2021.4.0), libvtk9.1 (>= 9.1.0+really9.1.0+dfsg2), libxerces-c3.2, libyaml-cpp0.7 (>= 0.7.0), libzipios++0v5
```

```
Package: libfreecad-daily-python3-1.1
Version: 1.1~pre1~202412111234~ubuntu22.04.1
Priority: optional
Section: libs
Source: freecad-daily
Maintainer: Debian Science Maintainers <debian-science-maintainers@lists.alioth.debian.org>
Installed-Size: 27.6 kB
Download-Size: 15.1 kB
APT-Manual-Installed: no
APT-Sources: https://ppa.launchpadcontent.net/freecad-maintainers/freecad-daily/ubuntu jammy/main amd64 Packages
```

This means that you won't get of the libocct packages.

**Comment by furgo16** [comment]
@mfraser thanks. I've found the related change at https://salsa.debian.org/adrianinsaval/freecad/-/commit/cf3785c41299eb55f867fae61033438beaa4aa47. I'm probably missing something, but at a quick glance I couldn't see what in the changes could have caused the missing declaration of dependencies.

**Comment by furgo16** [comment]
Regarding the original issue, I thought perhaps there is a repo that is not getting mirrored properly, but I cannot figure it out. Here's what I found out, in case it helps someone who's not the maintainer to debug:

1. The package is built from the [freecad-daily recipe](https://code.launchpad.net/~freecad-maintainers/+recipe/freecad-daily), which uses the [lp:freecad repository](https://code.launchpad.net/~freecad-maintainers/freecad/+git/freecad-salsa) on Launchpad. The `versioned-src/main` branch is used for the build.
2. The [lp:freecad repository](https://code.launchpad.net/~freecad-maintainers/freecad/+git/freecad-salsa) is a mirror of the https://salsa.debian.org/adrianinsaval/freecad repository on the Debian Salsa GitLab instance. It is imported twice a day.
3. TBD: the above repo is in turn a mirror of upstream FreeCAD. Need to find out the details.
4. There is an additional part at play: the Debian package source code (control file, rules, install scripts, etc) resides on that same https://salsa.debian.org/adrianinsaval/freecad repository, but in the [`ppa/main`](https://salsa.debian.org/adrianinsaval/freecad/-/tree/ppa/main?ref_type=heads) branch.
5. When the Debian package is built, Launchpad puts the contents of the `ppa/main` branch into a checkout of the `versioned-src/main` branch. This essentially adds the `debian` folder to the upstream FreeCAD code, and the Debian package is built from there.

**Comment by furgo16** [comment]
@mfraser I've reported what you mentioned in your comment as a separate issue here: https://github.com/FreeCAD/FreeCAD/issues/18455

**Comment by adrianinsaval** [comment]
The source in the salsa repo is definitively getting updated correctly, I can only guess that you still have lingering files from the previous install that showed up as 0.22 and that's why you get an old version

**Comment by adrianinsaval** [comment]
When I install the daily ppa now I get the latest version, can you try updating again? you might need to uninstall and reinstall again so that the dependency resolution works as it should

**Comment by furgo16** [comment]
I have indeed `libfreecad-daily-python3-0.22` installed, whereas all other packages are the `*-1.1` version. So this issue might be a duplicate of https://github.com/FreeCAD/FreeCAD/issues/18455. I'll wait until the next daily build that includes the fix and report back.

**Comment by furgo16** [comment]
I just noticed the PPA had been updated manually a few hours ago. After manually deleting `libfreecad-daily-python3-0.22` I can confirm that this bug is now fixed. It was indeed a duplicate of https://github.com/FreeCAD/FreeCAD/issues/18455

The shipped .deb packages now ship the code at the https://github.com/FreeCAD/FreeCAD/commit/d057fd79602acaa30a2b3e62cdac99b215cbd355 git hash (from yesterday), as expected.

**Comment by adrianinsaval** [comment]
did you need to manually uninstall the 0.22 version or did it got uninstalled upon update? I'm not quite sure why it was lingering there

**Comment by furgo16** [comment]
I had to manually uninstall `libfreecad-daily-python3-0.22` only

**Comment by gege2b** [comment]
> did you need to manually uninstall the 0.22 version or did it got uninstalled upon update? I'm not quite sure why it was lingering there

Hi
I had the same issue, doing `dpkg -r libfreecad-daily-python3-0.22` did the work and let the upgrade process to go fine

**Comment by luzpaz** [comment]
>> I had to manually uninstall `libfreecad-daily-python3-0.22` only

>  I had the same issue, doing `dpkg -r libfreecad-daily-python3-0.22` did the work and let the upgrade process to go fine

Should the PPA documentation be updated to inform the users about this ?

**Comment by dadour13** [comment]
thanks it's working well. good tips!!!
