### ISSUE TITLE
I am using freecad appimage in my ubuntu and cant access `mod` folder

### ISSUE THREAD

**Issue by hemangjoshi37a** [FreeCAD/FreeCAD-Bundle#357]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I am using freecad appimage in my ubuntu and cant access `mod` folder

Please help

### Full version info

```shell
NA
```

### Subproject(s) affected?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luzpaz** [comment]
Closing.
