### ISSUE TITLE
external projection geometry (Sketcher workbench) creates an actual geometry instead of projection.

### ISSUE THREAD

**Issue by kvacha13** [FreeCAD/FreeCAD-Bundle#358]
**Describe the bug**
In the latest weekly build, the external projection geometry (Sketcher workbench) creates an actual geometry instead of projection.

**To Reproduce**
1. Go to Part Design
2. Create any geometry (e.g circle) and extrude it
3. Create a sketch on extruded geometry and create an external projection geometry for the circle edge.
4. It creates actual cicle geometry instead of projection.

**Screenshots**
![image](https://github.com/user-attachments/assets/089f6792-804a-4402-b025-457a53f5126a)

**Comment by adrianinsaval** [comment]
not the place to report this
https://github.com/FreeCAD/FreeCAD-Bundle/issues/285
https://github.com/FreeCAD/FreeCAD-Bundle?tab=readme-ov-file#attention-this-is-not-the-freecad-bugtracker2

in any case I believe this is an intended feature (that has been requested many times for years), you can convert them to construction geometry if you want
