### ISSUE TITLE
Preferences error

### ISSUE THREAD

**Issue by mwganson** [FreeCAD/FreeCAD-Bundle#48]
When you go to Edit menu -> Preferences and press OK you get this error:

File "/tmp/.mount_FreeCApBjojb/usr/lib/python3.8/site-packages/freecad/appimage/init_gui.py", line 22, in saveSettings
preference_tabel.SetBool("appimage_auto_udpate", bool(self.form.always_check_updates.isChecked()))
<class 'AttributeError'>: ''PySide2.QtWidgets.QWidget' object has no attribute 'always_check_updates'

This is using 0.19 Revision 22756.  I can't copy/paste the full info because it's in a virtual machine.

**Comment by mwganson** [comment]
Reference to forum topic:

https://forum.freecadweb.org/viewtopic.php?f=3&t=51322

**Comment by antony-jr** [comment]
@looooo Please close this. This is resolved. @mwganson Please reopen if this exist even now(i.e test the latest version) which is not likely though.
