### ISSUE TITLE
OpenSCAD not working in AppImage

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-Bundle#56]
ticket: http://freecadweb.org/tracker/view.php?id=4343  
thread: https://forum.freecadweb.org/viewtopic.php?f=10&t=40848

**Comment by looooo** [comment]
we do not ship openscad with the appimage. This is still on the todo list. Therefore we would need to package openscad as a conda package. Otherwise one has to make sure openscad uses compatible (system) libs.

**Comment by luzpaz** [comment]
upstream: https://github.com/FreeCAD/FreeCAD_Conda/issues/19

**Comment by adrianinsaval** [comment]
we have lots of duplicates for this one 😆
