### ISSUE TITLE
libqhull_p.so.7 missing from AppImage v0.19-24267

### ISSUE THREAD

**Issue by atererus** [FreeCAD/FreeCAD-Bundle#59]
fatal error in AppImage FreeCAD 0.19 Revision: 24267 (Git) on Fedora 33 Workstation 5.10.19-200.fc33.x86_64
to reproduce : ./FreeCAD_0.19-24267 --run-test 0
to solve : yum install libqhull_p
IMHO libqhull_p should be in the appimage
forum : https://forum.freecadweb.org/viewtopic.php?p=487888
tracker : https://tracker.freecad.org/view.php?id=4542

**Comment by looooo** [comment]
never heared about this dependency. When was it introduced?

**Comment by pedromorgan** [comment]
Getting same error when I select "Reverse Engineering"..

```libqhull_p.so.7: cannot open shared object file: No such file or directory```

AppImage 0.19 on linux.. 24276(GIT) from 11.march 2021

**Comment by janis-ax** [comment]
+1

**Comment by luzpaz** [comment]
I guess this is the stable 0.19.3 AppImage from https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/0.19.3 right?  
Can you reproduce on the dev version ? https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/weekly-builds

**Comment by luzpaz** [comment]
Per the mantis ticket:  
```
1) Start FreeCAD from AppImage downloaded via Github
2) From the Workbench selector select "Reverse Engineering"
3) Observe the error / reverse engineering workbench not being loaded.
```

**Comment by adrianinsaval** [comment]
is this still relevant?

**Comment by atererus** [comment]
No it is about version 0.19

Op zaterdag 6 juli 2024 om 00:42 schreef Adrián Insaurralde Avalos ***@***.***>:
