### ISSUE TITLE
where to get the libpack matching FreeCAD_weekly-builds-24910

### ISSUE THREAD

**Issue by arthurx70** [FreeCAD/FreeCAD-Bundle#71]
where to get the libpack matching FreeCAD_weekly-builds-24291,the version of python in libpack is 3.8.6+,and the version of python in FreeCAD_weekly-builds is 3.8.8.

**Comment by luzpaz** [comment]
i dont think we create a libpack for the dev version. The windows build in this repo is created from conda (different than how the stable builds are created). Am i right, @looooo ?

**Comment by looooo** [comment]
> The windows build in this repo is created from conda (different than how the stable builds are created). Am i right, @looooo ?

stable builds are also from conda. It's the same procedure. But there are alternatives to conda. 

I close this issue. Feel free to reopen if this is still an issue.
