### ISSUE TITLE
filllet feature is wrong after transformed.

### ISSUE THREAD

**Issue by LeoBinsc** [FreeCAD/FreeCAD-Bundle#72]
when useing  'linearPattern' part  in   'create a multitransform feature' , filllet feature is wrong after transformed.
![2021-06-08_183319](https://user-images.githubusercontent.com/45816907/121170930-704af480-c888-11eb-9315-10caf35709d0.png)
![2021-06-08_183505](https://user-images.githubusercontent.com/45816907/121170962-793bc600-c888-11eb-9b9a-2479884c5e84.png)

**Comment by luzpaz** [comment]
This is an issue queue for FreeCAD **packaging** not for FreeCAD in general. Please read the [guidelines](https://wiki.freecadweb.org/tracker) of how to report bugs to the project. Hint: Fillets and Lofts are quirky in FC, there are several open tickets related to the OpenCasCade CAD kernel that we rely on.
