### ISSUE TITLE
Change the description of this repo

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-Bundle#75]
![image](https://user-images.githubusercontent.com/4140247/131723261-cb0be240-0f17-413b-bdca-96ec69c258a9.png)

It is more than just the appimage...

**Comment by luzpaz** [comment]
@looooo bump

**Comment by sgrogan** [comment]
This is me. We have the (conda-based) AppImage of course, but also the conda-based .dmg and .7z. In addition I use the releases to publish Libpack based assets, although there is nothing in the repo that supports this. As you know we also do some experimental/convenience packaging here like glider and asm3.

We have a better name now. I'll try to come up with something better for the description. As you all know I'm no wordsmith, so we would, of course, entertain pull requests.

**Comment by luzpaz** [comment]
you can't submit PRs to change the repository descriptions :sweat_smile:

**Comment by luzpaz** [comment]
@sgrogan how about: `Weekly generated FreeCAD development builds for testing the latest features/bug fixes` ?

**Comment by luzpaz** [comment]
@sgrogan ping

**Comment by luzpaz** [comment]
@looooo can you give me permissions to be able to change stuff like this?

**Comment by looooo** [comment]
sry, I don't have the permission to do this. Maybe pinging @yorikvanhavre

**Comment by luzpaz** [comment]
@yorikvanhavre we need to update the repo description.

**Comment by luzpaz** [comment]
@yorikvanhavre ping. If you need help, I'm happy to update. I need privs though.

**Comment by yorikvanhavre** [comment]
Sorry, forgot this... What about this?
![image](https://user-images.githubusercontent.com/1136856/221582670-3804903f-d3ac-422e-9ad4-0acbf86a7668.png)
