### ISSUE TITLE
Bug in Sketch module?

### ISSUE THREAD

**Issue by wzaburko** [FreeCAD/FreeCAD-Bundle#76]
Sorry my english is not very good.
I create a box.
I made changes to Sketch003 and after that my design was deformed. Something happened to the first Sketch that I didn't edit and that was done first. I tried to delete all the lofts and do it all over again but failed.
Something is happening with the Sketch module. I've had it a few times but "recalculation" of the object helped.
Try to change the order Pad001 should be first, You can try to change the loft length, delete and make again loft to Sketch and Sketch003 and see what happens.
After editing "Sketch" or recalculation, it seems to be back to "normal" but I can't loft on Sketch003.

[test.zip](https://github.com/FreeCAD/FreeCAD-Bundle/files/7176451/test.zip)

FreeCAD_weekly-builds-25645-Linux-Conda_glibc2.12-x86_64
Ubuntu 21.04

**Comment by chennes** [comment]
Hello @wzaburko -- You'll want to post this on the FreeCAD Forums in the "Help on using FreeCAD" area: https://forum.freecadweb.org/viewforum.php?f=3
