### ISSUE TITLE
weird behavior of 'Loft' interacting with 'Linear Patern' and such since 0.20

### ISSUE THREAD

**Issue by discip** [FreeCAD/FreeCAD-Bundle#78]
Good evening,
first of all thank you for this great software!

Despite the greatly welcomed improvements, I have to report an issue concerning the **`loft`** feature interacting with **`linear pattern`**, **`polar pattern`** & **`multi transform`**.

As you can observe in the attached files, **`linear pattern`** only works for an **`additive  loft`** if it is either
1. directly on top of the **`pad`** (0 distance) or
2. if it is intersecting the **`pad`** it has to intersect the **`linear patterned`** part as well.

However this does not apply to **`extruded`** objects!

Happy to answer questions, if I was not able to make myself clear enough. 😊

I am on: [FreeCAD_weekly-builds-25943-Win-Conda_vc14.x-x86_64.7z](https://github.com/FreeCAD/FreeCAD-Bundle/releases/download/weekly-builds/FreeCAD_weekly-builds-25943-Win-Conda_vc14.x-x86_64.7z)

thanks in advance
kind regards
[examples.zip](https://github.com/FreeCAD/FreeCAD-Bundle/files/7306921/examples.zip)

**Comment by 3mandd** [comment]
Hey, 
I think the way it goes with FreeCAD,
you have to discuss here: https://forum.freecadweb.org/viewforum.php?f=8
and once confirmed, make bug report

**Comment by discip** [comment]
@3mandd
Thanks, will try.

**Comment by luzpaz** [comment]
Indeed:
![image](https://user-images.githubusercontent.com/4140247/136469972-7d5f34db-53c4-4f82-a6f7-94a9edb930ea.png)
Please see https://wiki.freecad.org/Tracker

Closing ticket as offtopic
