### ISSUE TITLE
FreeCAD weekly-builds-Unknown

### ISSUE THREAD

**Issue by bitacovir** [FreeCAD/FreeCAD-Bundle#83]
The download files of FreeCAD weekly-builds have lost their version numbers. 
See https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/weekly-builds

**Comment by luzpaz** [comment]
screenshot:

![image](https://user-images.githubusercontent.com/4140247/139980889-9d79bf2a-ca32-4857-a12d-8c9dfcf511c9.png)

**Comment by looooo** [comment]
fixed
