### ISSUE TITLE
Reverse hole with thread gives error

### ISSUE THREAD

**Issue by judge2005** [FreeCAD/FreeCAD-Bundle#88]
I can't create a threaded hole with the 'reverse' option checked. I get this error:

![Screen Shot 2022-01-22 at 12 34 38 PM](https://user-images.githubusercontent.com/294515/150649456-8ee263eb-f3b5-430a-aee5-b6151b231fce.png)

I've attached a sample file that reproduces the issue. Just try to make the hole 'reversed'

OS: macOS 10.16
Word size of FreeCAD: 64-bit
Version: 0.20.27078 (Git)
Build type: Release
Python version: 3.9.9
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.5.3
Locale: C/Default (C)

[20-hole.FCStd.zip](https://github.com/FreeCAD/FreeCAD-Bundle/files/7918937/20-hole.FCStd.zip)

**Comment by luzpaz** [comment]
Not a bug tracker for freecad. Please open a thread on the forum.freecad.org  
Thank you.
