### ISSUE TITLE
Glider breaks most recent weekly builds

### ISSUE THREAD

**Issue by KenwoodFox** [FreeCAD/FreeCAD-Bundle#93]
This could be a system problem but im not sure, after updating recently using the aur package for the weekly appimage builds, im getting lots of instability, screen shows black and i get this error in the logs. Frequent crashes, i know the weekly builds are buggy but i cant help but imagine this is more than the usual.

```
During initialization the error "expected str, bytes or os.PathLike object, not list" occurred in freecad.freecad_glider
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "<string>", line 238, in InitApplications
  File "/tmp/.mount_freecasZWZJ6/usr/lib/python3.9/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not list
--------------------------------------------------------------------------------
```

**Comment by luzpaz** [comment]
Please post full [about](https://wiki.freecad.org) info. 
This looks like issue in @looooo's Glider workbench

**Comment by KenwoodFox** [comment]
... What?

Your about link goes to the freecad wiki homepage,

Is this an OpenGlider bug? is that a plugin? Im just using the stock appimage.

Im not compiling the appimage locally, this is from here.

**Comment by KenwoodFox** [comment]
```
FreeCAD 0.20, Libs: 0.20R27809 (Git)
```
![image](https://user-images.githubusercontent.com/31870999/156270322-f05c45a5-a9b1-47e6-a6b5-353f0ace9d0a.png)

**Comment by luzpaz** [comment]
Glider WB is @looooo's baby. It's is only active when built from conda. 


BTW, my bad, .i guess this is the place to report your issue because FreeCAD-appimage repo was renamed to FreeCAD-Bundle.  Forgot about that.

**Comment by KenwoodFox** [comment]
No worries! I was just confused for a momen~ So the builds here do include this bug?
I know they're weekly releases and can be buggy but this seems to be pretty nasty, anything we can do?

**Comment by luzpaz** [comment]
I guess, wait till @looooo sees this ?? :laughing:

**Comment by KenwoodFox** [comment]
My favorite kind of solution :rofl: the one where i just wait for somebody else to fix it~

LMK if i can do anything ill throw a PR together if needed

**Comment by luzpaz** [comment]
BTW, these days I'm using the Snap package, the nightly 'edge' version. 
Try it, it updates nightly automagically
`snap install --edge freecad-ppd`

**Comment by KenwoodFox** [comment]
> BTW, these days I'm using the Snap package, the nightly 'edge' version. Try it, it updates nightly automagically `snap install --edge freecad-ppd`

My religion is against snap :P so ill wait/make a pr to fix the appimage~

**Comment by KenwoodFox** [comment]
Could i remove glider from the bundle? 

https://github.com/FreeCAD/FreeCAD-Bundle/blob/8e28d9ad26b500b5d2ebd1645ac6b00279ef358e/conda/linux/create_bundle.sh#L8

**Comment by KenwoodFox** [comment]
Having trouble figuring out how to build locally, is there a guide?

**Comment by looooo** [comment]
I guess this is related to a change on the freecad side. But the trace-back does not give a good hint what's wrong.

**Comment by KenwoodFox** [comment]
Is there any more information i can get? More verbose logs? @looooo

**Comment by looooo** [comment]
> Is there any more information i can get? More verbose logs? @looooo

checking the log file, but there is not a lot of information. I guess the issue is this line:
https://github.com/FreeCAD/FreeCAD/blob/master/src/App/FreeCADInit.py#L238

It was introduces with this commit:
https://github.com/FreeCAD/FreeCAD/commit/02cfa11c8e23427874ea5c910817da91a505afa7

I hope @chennes can explain the changes.

**Comment by luzpaz** [comment]
That looks like code chennes touched recently for the Addon Manager

**Comment by chennes** [comment]
Yeah, that line is wrong: I've removed it in https://github.com/FreeCAD/FreeCAD/commit/3af20938cd3dec19fe2a30750bce101fec0db18c

**Comment by KenwoodFox** [comment]
Thats good news! Next time bunlder runs it should be fixed?

**Comment by KenwoodFox** [comment]
Cron says the next build is sunday, any chance we could hit it with a manual run?

**Comment by chennes** [comment]
I think that's @looooo if he's around

**Comment by KenwoodFox** [comment]
Sorry to bug so much, i would apprecaite it a lot!

**Comment by looooo** [comment]
I will trigger a new build. New bundle will be available tomorrow.

**Comment by KenwoodFox** [comment]
Sweet~

**Comment by looooo** [comment]
@KenwoodFox can you try again. Bundles are updated

**Comment by KenwoodFox** [comment]
Yep! Just tried when i woke up, the aur package brought it down.

There is no longer any issues in the log, and it looks a bit better, the start screen still does not work but you clearly fixed the path bug.

![image](https://user-images.githubusercontent.com/31870999/156571539-faf13dfa-1989-4f03-a609-9a694a237c15.png)
![image](https://user-images.githubusercontent.com/31870999/156571594-ef69c15e-607d-4ac6-8a7b-60242618c773.png)

**Comment by luzpaz** [comment]
Start page issue is reported in #97 

Can we close this ticket?

**Comment by KenwoodFox** [comment]
Yep! Ill subscrube to #97
