### ISSUE TITLE
v0.19.4 has been released 

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-Bundle#94]
https://github.com/FreeCAD/FreeCAD/releases/tag/0.19.4

**Comment by looooo** [comment]
I have troubles with the build process. Windows is working, but Linux and osx fail.

**Comment by luzpaz** [comment]
errors?

**Comment by looooo** [comment]
https://github.com/conda-forge/freecad-feedstock/pull/65

**Comment by MasterCATZ** [comment]
I could not get 19.4 to build and 
./FreeCAD_0.19.3-Linux-Conda_glibc2.12-x86_64.AppImage 
FreeCAD 0.19, Libs: 0.19R24366 (Git)
is just a black screen ... 

![Screenshot from 2022-03-04 22-50-37](https://user-images.githubusercontent.com/1857824/156766709-9b77232d-dc4f-4394-88f1-c75ffa7f6bc8.png)

**Comment by rastersoft** [comment]
In the official page, the AppImage version available is still 19.3, and doesn't work in Debian since today at least. The reason seems to be an update to libstdc++6.

As commented in other closed issues, a way of workaround this is to launch it with

    LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libstdc++.so.6 ./FreeCAD_0.19.3-Linux-Conda_glibc2.12-x86_64.AppImage

(or the path to the libstdc++.so.6 file if your system put it in another place, of course).

**Comment by speendo** [comment]
Thanks for this hint!
This bug kept me from working on my projects in the last days.

I hope there will be a fix soon.

Also, this information should be on a more prominent place...

**Comment by luzpaz** [comment]
I've updated the 0.19.3 Release text to reflect the stdc++6 workaround.

![Screenshot_20220403_074251](https://user-images.githubusercontent.com/4140247/161426280-2315dad4-7704-457c-be5b-ceeac7e24f92.png)

**Comment by adrianinsaval** [comment]
this can be closed @luzpaz
